---
- name: Generate vsphere.conf
  template:
    src: vsphere.conf.j2
    dest: "/etc/kubernetes/vsphere.conf"
    mode: '0644'
    owner: root
    group: root

- name: Create configmap
  command: "kubectl create configmap cloud-config --from-file=/etc/kubernetes/vsphere.conf --namespace=kube-system"

- name: Check configmap
  command: "kubectl get configmap cloud-config --namespace=kube-system"

- name: Generate cpi-global-secret.yaml
  template:
    src: cpi-global-secret.yaml.j2
    dest: "/root/cpi-global-secret.yaml"
    mode: '0644'
    owner: root
    group: root

- name: Create secret
  command: "kubectl create -f /root/cpi-global-secret.yaml"

- name: Check secret
  command: "kubectl get secret cpi-global-secret --namespace=kube-system"

- name: Check node taint
  shell: 'kubectl describe nodes | egrep "Taints:|Name:" | egrep "kubernetes.io/master:NoSchedule"'

- name: Apply cloud controller manager role manifest
  command: "kubectl apply -f https://raw.githubusercontent.com/kubernetes/cloud-provider-vsphere/master/manifests/controller-manager/cloud-controller-manager-roles.yaml"

- name: Apply cloud controller role binding manifest
  command: "kubectl apply -f https://raw.githubusercontent.com/kubernetes/cloud-provider-vsphere/master/manifests/controller-manager/cloud-controller-manager-role-bindings.yaml"

- name: Apply cloud controller manager daemon set manifest
  command: "kubectl apply -f https://github.com/kubernetes/cloud-provider-vsphere/raw/master/manifests/controller-manager/vsphere-cloud-controller-manager-ds.yaml"
  #command: "kubectl apply -f https://raw.githubusercontent.com/kubernetes/cloud-provider-vsphere/master/manifests/controller-manager/vsphere-cloud-controller-manager-ds.yaml"

- name: Check worker node taint
  tags: "cpi-taint"
  shell:
    cmd: '(( $(kubectl describe nodes | egrep "Taints:|Name:" | awk "/worker/{getline; print}" | egrep "<none>" | wc -l) == "{{ worker_count }}"))'
    executable: "/bin/bash"
  register: workertaint
  retries: 10
  delay: 5
  until: workertaint.rc == 0

- name: Check master node taint
  tags: "cpi-taint"
  shell:
    cmd: '(( $(kubectl describe nodes | egrep "Taints:|Name:" | awk "/master/{getline; print}" | egrep "node-role.kubernetes.io/master:NoSchedule" | wc -l) == "{{ master_count }}"))'
    executable: "/bin/bash"
  register: mastertaint
  retries: 10
  delay: 5
  until: mastertaint.rc == 0

- name: Check ProviderID
  tags: "provider-id"
  shell: "kubectl describe nodes | grep 'ProviderID'"
  register: provider
  retries: 10
  delay: 5
  until: provider.rc == 0
