---
- name: Update All Packages to their Latest Version
  apt:
    name: "*"
    state: latest
    update_cache: yes
  register: result
  retries: 3
  delay: 10
  until: result is not failed

- name: Install HA-Proxy
  apt:
    name: haproxy
    state: present
  register: result
  retries: 3
  delay: 10
  until: result is not failed

- name: Save HA-Proxy Configuration
  command: mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.back

- name: Set HA-Proxy Configuration
  shell: echo "{{ lookup('template', 'haproxy.j2') }}" > /etc/haproxy/haproxy.cfg

- name: Allow System Services Binding on the Non-Local IP
  shell: echo "net.ipv4.ip_nonlocal_bind=1" >> /etc/sysctl.conf

- name: Apply Services Binding
  shell: sysctl -p
  register: result
  retries: 3
  delay: 10
  until: result is not failed

- name: Enbale HA-Proxy
  systemd:
    name: haproxy
    enabled: yes

- name: Start HA-Proxy
  systemd:
    name: haproxy
    state: started

- name: Reboot Etcd Nodes
  community.vmware.vmware_guest_powerstate:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    folder: "<folder>"
    name: "{{ vm_guestname | default(omit) }}"
    state: reboot-guest
  delegate_to: localhost
  register: deploy

- name: Ensure Nodes are Up and Running
  wait_for:
    host: "{{ guest_custom_ip }}"
    port: 22
    delay: 30
    timeout: 300
  delegate_to: localhost

- name: Check whether HA-Proxy Started
  shell: "netstat -ntlp | grep {{ endpoint }}"
  delay: 5
