---
- name: Create temp directories to store files that will end up on other hosts
  file:
    path: "/tmp/{{ hostvars[item]['guest_custom_ip']  }}"
    recurse: yes
    mode: '0700'
    owner: root
    group: root
  loop: "{{ groups['etcd'] }}"

- name: Deploy kubeadm configuration file for each node
  template:
    src: kubeadmcfg.yaml.j2
    dest: "/tmp/{{ hostvars[item]['guest_custom_ip'] }}/kubeadmcfg.yaml"
    mode: '0644'
    owner: root
    group: root
  loop: "{{ groups['etcd'] }}"
